[project]
name = "hallucinator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bert-score>=0.3.13",
    "groq>=0.25.0",
    "nltk>=3.8.1",
    "numpy>=2.2.6",
    "torch>=2.1.0",
    "transformers>=4.36.0",
]
